name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest
        pip install -r requirements.txt
    - name: Lint
      run: |
        black . -l 79 --check --diff --exclude '/(\.md|\.yml|\.png|\.txt)/'
    - name: Test
      env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          VERIFY_TOKEN: ${{ secrets.VERIFY_TOKEN }}
      run: |
        for file in app/tests/*
        do
          python -m pytest $file
        done